name: Deploy

# Trigger the workflow on push and
# pull request events on the production branch
on:
  push:
    branches:
      - production


# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Composer
      uses: php-actions/composer@v6
      with:
        dev: no
        interaction: no
        args: --prefer-dist --optimize-autoloader
    - name: Set up Node
      uses: actions/setup-node@v4.0.1
    - run: npm install -D tailwindcss postcss autoprefixer
    - run: npm run build
    - name: Commit built assets
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -B deploy
        git add -f public/
        git add package-lock.json
        git commit -m "Build front-end assets"
        git push -f origin deploy
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: "cd /home/u9-7tfzpstrxnlx/www/gestionalepf.pythonsrl.com/public_html && ./server_deploy.sh"

