            - name: Laravel Deploy
  # You may pin to the exact commit or the version.
  # uses: ngocquyhoang/laravel-deploy@4f064451375ad4217ad7ce333b4f6074a152fbc6
  uses: ngocquyhoang/laravel-deploy@laravel
  with:
    # Deploy user
    user: 
    # Deploy host
    host: 
    # Path source on server
    path: 
    # Deploy owner
    owner: 
          
